# -*- coding: utf-8 -*-
"""ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qP1hunIVD2cTEzkjt4Yh1NitKpRQWqVQ
"""

# Cell 1: Install git (already in Colab) + setup your info
!git config --global user.email "glo.wan.kih@gmail.com"   # ← CHANGE THIS
!git config --global user.name "Kaaybe"              # ← CHANGE THIS

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import r2_score, mean_absolute_error
# from sklearn.impute import SimpleImputer
# 
# st.set_page_config(page_title="ML Linear Regression", layout="wide")
# st.title("Linear Regression Model")
# 
# file = st.file_uploader("Upload CSV (last column = target)", type="csv")
# if file:
#     df = pd.read_csv(file)
#     X = df.iloc[:, :-1].select_dtypes(include=np.number)
#     y = df.iloc[:, -1]
# 
#     imp = SimpleImputer(strategy="mean")
#     X = pd.DataFrame(imp.fit_transform(X), columns=X.columns)
# 
#     model = LinearRegression().fit(X, y)
#     pred = model.predict(X)
# 
#     st.success(f"R² Score: {r2_score(y, pred):.3f} | MAE: {mean_absolute_error(y, pred):,.0f}")
# 
#     st.write("### Predict New Value")
#     inputs = [st.number_input(c, value=float(X[c].mean())) for c in X.columns]
#     if st.button("Predict"):
#         p = model.predict([inputs])[0]
#         st.balloons()
#         st.success(f"Prediction: **{p:,.2f}**")
# else:
#     st.info("Upload a CSV file to train the model")

!git remote add origin https://github.com/Kaaybe/ai_data_analyzer